import {
  pgTable,
  pgEnum,
  uuid,
  varchar,
  char,
  boolean,
  integer,
  numeric,
  serial,
  timestamp,
} from "drizzle-orm/pg-core";
import { relations } from "drizzle-orm";

// ─── Enums ─────────────────────────────────────────────────────
export const userRoleEnum = pgEnum("user_role", ["customer", "admin", "cashier"]);

// ─── Tables ────────────────────────────────────────────────────

/**
 * users (profiles)
 * Primary key is a UUID generated by Better Auth on sign-up.
 */
export const users = pgTable("users", {
  id: uuid("user_id").primaryKey().defaultRandom(),
  name: varchar("name", { length: 150 }).notNull(),
  email: varchar("email", { length: 150 }).notNull().unique(),
  phoneNumber: varchar("phone_number", { length: 20 }),
  role: userRoleEnum("role").notNull().default("customer"),
  emailVerified: boolean("is_email_verified").notNull().default(false),
  image: varchar("profile_picture", { length: 512 }),
  loyaltyPoints: integer("loyalty_points").notNull().default(0),
  creditBalance: numeric("credit_balance", { precision: 10, scale: 2 }).notNull().default("0.00"),
  totalSpent: numeric("total_spent", { precision: 12, scale: 2 }).notNull().default("0.00"),
  lastLoginAt: timestamp("last_login_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});

/**
 * user_addresses
 * Separate table so each user can save multiple shipping addresses.
 * Shipping info is snapshotted on the orders table at checkout — address
 * changes here do NOT affect historical order data.
 */
export const userAddresses = pgTable("user_addresses", {
  addressId: serial("address_id").primaryKey(),
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  label: varchar("label", { length: 50 }), // e.g. Home, Work
  fullName: varchar("full_name", { length: 150 }).notNull(),
  phoneNumber: varchar("phone_number", { length: 20 }).notNull(),
  addressLine1: varchar("address_line1", { length: 255 }).notNull(),
  addressLine2: varchar("address_line2", { length: 255 }),
  city: varchar("city", { length: 100 }).notNull(),
  state: varchar("state", { length: 100 }).notNull(),
  pincode: varchar("pincode", { length: 15 }).notNull(),
  countryCode: char("country_code", { length: 2 }).notNull().default("IN"),
  isDefault: boolean("is_default").notNull().default(false),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});

/**
 * loyalty_transactions
 * Audit log for every loyalty point / credit balance change.
 */
export const loyaltyTransactionTypeEnum = pgEnum("loyalty_transaction_type", [
  "earned",       // Points earned from purchase
  "redeemed",     // Points/credit used at checkout
  "credit_added", // Manual credit added by admin
  "credit_used",  // Credit used on a bill
  "adjustment",   // Manual admin adjustment
  "expired",      // Points expired
]);

export const loyaltyTransactions = pgTable("loyalty_transactions", {
  transactionId: serial("transaction_id").primaryKey(),
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  type: loyaltyTransactionTypeEnum("type").notNull(),
  points: integer("points").notNull().default(0),
  creditAmount: numeric("credit_amount", { precision: 10, scale: 2 }).notNull().default("0.00"),
  description: varchar("description", { length: 255 }).notNull(),
  referenceId: varchar("reference_id", { length: 100 }), // bill ID, order ID, etc.
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});

// ─── Relations ─────────────────────────────────────────────────

export const usersRelations = relations(users, ({ many }) => ({
  addresses: many(userAddresses),
  loyaltyTransactions: many(loyaltyTransactions),
}));

export const userAddressesRelations = relations(userAddresses, ({ one }) => ({
  user: one(users, {
    fields: [userAddresses.userId],
    references: [users.id],
  }),
}));

export const loyaltyTransactionsRelations = relations(loyaltyTransactions, ({ one }) => ({
  user: one(users, {
    fields: [loyaltyTransactions.userId],
    references: [users.id],
  }),
}));